train:
  dataloader:
    csv: /home/intern0/Desktop/project/IITP/Sound_source_localization/Data_processing/speech_setup/dataset/tr.csv
    batch_size: 32
    shuffle: True
    num_workers: 4
    drop_last: False
    audio_path: /home/intern0/Desktop/project/IITP/Sound_source_localization/Data_processing/speech_setup/dataset
    duration: 64000


  

  optimizer:
    type: Adam
    learning_rate: 1e-4
    weight_decay: 1e-7

  loss: SI-SNR

FFT:
  window_size: 512
  hop_size: 256
val:
  dataloader:
    csv: /home/intern0/Desktop/project/IITP/Sound_source_localization/Data_processing/speech_setup/dataset/cv.csv
    batch_size: 32
    shuffle: False
    num_workers: 4
    drop_last: False
    audio_path: /home/intern0/Desktop/project/IITP/Sound_source_localization/Data_processing/speech_setup/dataset
    duration: 64000

test:
  FFT:
    window_size: 512
    hop_size: 256
  model:
    type: CRNN
    trained: /home/intern0/Desktop/project/IITP/Beamformer/exp_result/2021_09_08_20_59_15/6_model.tar

  dataloader:
    csv: /home/intern0/Desktop/project/IITP/Sound_source_localization/Data_processing/speech_setup/dataset/tt.csv
    batch_size: 1
    shuffle: False
    num_workers: 4
    drop_last: False
    audio_path: /home/intern0/Desktop/project/IITP/Sound_source_localization/Data_processing/speech_setup/dataset
    duration: None


exp:
  result: ./exp_result/
  epoch: 300
  model: CRNN