optimizer:
  type: Adam
  gradient_clip: 1
  config:
    lr: 1.0e-4
    weight_decay: 1.0e-6

 

optimizer_scheduler:
  type: ReduceLROnPlateau
  config:
    mode: 'min'
    factor: 0.9
    patience: 4000000
    threshold: 1.0e-8
    min_lr: 1.0e-4
    verbose: True
    
loss: 
  optimize_method: 'min'
  type: SI-SDR
 