train:

  speech_dir: /librispeech/LibriSpeech/train-clean-100/
  noise_dir: //MS_SNSD/train/ 
  vad_dir: /librispeech/LibriSpeech/vad_by_webrtcpy_1005/train-clean-100/

  iteration_num_per_epoch: 200000

  metadata_dir: ./metadata/
  noise_csv: noise_train.csv
  speech_csv: librispeech_train.csv
  

  ans_azi: 0
  degree_resolution: 1

  dataloader_dict:
    batch_size: 16 #16
    shuffle: True
    num_workers: 8 #6
    drop_last: True

  mic_type: circular # circular,. ellipsoid, linear
  mic_num: 4 # 4, 6, 8
  max_n_mic: 4
  max_spk: 1
  speech_least_chunk_size: 32000

  SNR: [0, 40]
  spk_SNR: [-5, 5]
  without_coherent_noise: [1.0, 0.0]
  white_noise_snr: [5, 70]
  normalize_factor: [0.004, 1.0]
  fs: 16000
  duration: 64000 # 4s
  early_reverb: 40 # ms  

  

  gpu_rir_characteristic: 
      
    rt60_bound: [0.2, 1.3]
    abs_weights_bound: [0.5, 1.0]
    room_sz_bound: [[2.0, 1.0, 0.7], [15.0, 15.0, 7.0]]
      
    azi_gap: 30

    array_pos: 
      x: [0.1, 0.9]
      y: [0.1, 0.9]
      z: [0.1, 0.5]
    mic:
      rotation: True
     
      mic_height: [0.3, 1.2]
      mic_from_wall: 0.2

    ref_vec: 0
    room:
      distance: [0.3, 2.0] # m
      azimuth: [0, 180, 1] # start, end, unit # degree
      elevation: [30, 100, 1]  
      

    gpu_rir_generate_dict: # input of gpu rir
      room_sz:
      beta:
      pos_src:
      pos_rcv:
      nb_img:
      Tmax:
      fs: 16000.0
      c: 343.0
      orV_rcv:
      mic_pattern: omni 






test:
  # noise_dir: /root/harddisk1/DB_custom/IITP/MS_SNSD/cv/

  # pkl_dir: /root/harddisk1/DB_custom/IITP/SSL/val_DB/
  # vad_dir: /root/harddisk1/Dataset/sitec/vad_by_webrtcpy/
  # speech_dir: /root/harddisk1/Dataset


  # 1005 workstation
  speech_dir: /root/harddisk1/Dataset/librispeech/LibriSpeech/test-clean/
  noise_dir: /root/share/share/IITP/MS_SNSD/cv/ 
  # vad_dir: /root/ssd2/baek/Baek/vad/test-clean/
  pkl_dir: /root/harddisk1/DB_custom/Beamforming/circle_4/cv/  # circular, ellipsoid, linear


  metadata_dir: ./metadata/
  noise_csv: noise_cv.csv
  speech_csv: cv_audio_list.csv
  pkl_csv: val_csv_circular_4.csv
  # speech_csv: librispeech_test.csv

  ans_azi: 0
  degree_resolution: 1

  dataloader_dict:
    batch_size: 16 #16
    shuffle: False
    num_workers: 0 # 6
    drop_last: True

  mic_type: circular # circular,. ellipsoid, linear
  mic_num: 4 # 4, 6, 8
  max_n_mic: 4
  max_spk: 1
  speech_least_chunk_size: 32000

  SNR: [0, 40]
  spk_SNR: [-5, 5]
  without_coherent_noise: [1.0, 0.0]
  white_noise_snr: [5, 70]
  normalize_factor: [0.004, 1.0]
  fs: 16000
  duration: 64000 # 4s
  early_reverb: 40 # ms   
  
  
  gpu_rir_characteristic: 
      
    rt60_bound: [0.2, 1.3]
    abs_weights_bound: [0.5, 1.0]
    room_sz_bound: [[2.5, 2.5, 2.5], [15.0, 15.0, 7.0]]
      
    azi_gap: 30

    array_pos: #[[0.1, 0.1, 0.1], [0.9, 0.9, 0.5]]
      x: [0.1, 0.9]
      y: [0.1, 0.9]
      z: [0.1, 0.5]
    mic:
      rotation: True
      mic_type: eigenmike_size_8_array
      mic_height: [0.3, 1.2]
      mic_from_wall: 0.3

    ref_vec: 90
    room:
      distance: [0.3, 2.0] # m
      azimuth: [0, 180, 1] # start, end, unit # degree
      elevation: [30, 100, 1]   

    gpu_rir_generate_dict: # input of gpu rir
      room_sz:
      beta:
      pos_src:
      pos_rcv:
      nb_img:
      Tmax:
      fs: 16000.0
      c: 343.0
      # orV_rcv: None
      mic_pattern: omni 